const images = [
    {id: '01d', src: './01d.png'},
    {id: '01n', src: './01n.png'},
    {id: '02d', src: './02d.png'},
    {id: '02n', src: './02n.png'},
    {id: '03d', src: './03d.png'},
    {id: '03n', src: './03n.png'},
    {id: '04d', src: './04d.png'},
    {id: '04n', src: './04n.png'},
    {id: '09d', src: './09d.png'},
    {id: '09n', src: './09n.png'},
    {id: '10d', src: './10d.png'},
    {id: '10n', src: './10n.png'},
    {id: '11d', src: './11d.png'},
    {id: '11n', src: './11n.png'},
    {id: '13d', src: './13d.png'},
    {id: '13n', src: './13n.png'},
    {id: '50d', src: './50d.png'},
    {id: '50n', src: './50n.png'},
]

// const images = [
//     {id: '01d', src: './weather-images/01d.png'},
//     {id: '01n', src: './weather-images/01n.png'},
//     {id: '02d', src: './weather-images/02d.png'},
//     {id: '02n', src: './weather-images/02n.png'},
//     {id: '03d', src: './weather-images/03d.png'},
//     {id: '03n', src: './weather-images/03n.png'},
//     {id: '04d', src: './weather-images/04d.png'},
//     {id: '04n', src: './weather-images/04n.png'},
//     {id: '09d', src: './weather-images/09d.png'},
//     {id: '09n', src: './weather-images/09n.png'},
//     {id: '10d', src: './weather-images/10d.png'},
//     {id: '10n', src: './weather-images/10n.png'},
//     {id: '11d', src: './weather-images/11d.png'},
//     {id: '11n', src: './weather-images/11n.png'},
//     {id: '13d', src: './weather-images/13d.png'},
//     {id: '13n', src: './weather-images/13n.png'},
//     {id: '50d', src: './weather-images/50d.png'},
//     {id: '50n', src: './weather-images/50n.png'},
// ]

export default images;